In [36]:
import numpy as np

In [37]:
a=np.array([1,2,3,4])
b=np.array([4,2,7,3])

In [38]:
print("a: ",a)
print("b: ",b)

a:  [1 2 3 4]
b:  [4 2 7 3]


In [39]:
#sum
a_add=a+3
a_add


array([4, 5, 6, 7])

In [40]:
addition= a+b
print(addition)

[ 5  4 10  7]


In [41]:
a_add_b=np.add(a,b)
a_add_b

array([ 5,  4, 10,  7])

In [42]:
multiply= a*b
print(multiply)

[ 4  4 21 12]


In [43]:
m=b*3
m

array([12,  6, 21,  9])

In [44]:
a_m_b=np.multiply(a,b)
a_m_b

array([ 4,  4, 21, 12])

In [45]:
reci=np.reciprocal(a)
reci

array([1, 0, 0, 0])

In [46]:
reci2=np.reciprocal(b)
reci2

array([0, 0, 0, 0])

In [47]:
c=np.array([0.5,0.75,0.25])
c

array([0.5 , 0.75, 0.25])

In [49]:
reci3=np.reciprocal(c)
reci3

array([2.        , 1.33333333, 4.        ])

In [50]:
a


array([1, 2, 3, 4])

In [51]:
print(np.min(a))

1


In [53]:
print(np.max(a))

4


In [54]:
#position of min element
print(np.argmin(a))

0


In [55]:
#position of max element
print(np.argmax(a))

3


In [56]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.        ]


In [57]:
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
