In [1]:
import numpy as np

In [2]:
ar=np.array([1,2,3,4])

In [4]:
print(ar)

[1 2 3 4]


In [5]:
#tells the type which is numpy.ndarray
print(type(ar))

<class 'numpy.ndarray'>


In [6]:
#tells the no. of dimensions an array have
print(ar.ndim)

1


In [12]:
#if you are trying to make a 2D array but the no of values differ in both rows then the output will be an 1D array containing list
# depends on software  
er=np.array([[1,2,3,4],[4,3,2]])
print(er)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [16]:
#2D array 
ar2=np.array([[1,2,3,4],[4,3,2,1]])
print(ar2)
print("no of dimaensions:",ar2.ndim)

[[1 2 3 4]
 [4 3 2 1]]
no of dimaensions: 2


In [18]:
#3D array
ar3=np.array([[[1,2,3]]])
print(ar3)
print("no of dimaensions:",ar3.ndim)

[[[1 2 3]]]
no of dimaensions: 3


In [19]:
#n dimension array
arn=np.array([2,3,4],ndmin=10)
print(arn)
print("no of dimaensions:",arn.ndim)

[[[[[[[[[[2 3 4]]]]]]]]]]
no of dimaensions: 10
