In [20]:
import numpy as np

conditions:
    1) dimensions should be same
    2) if dimensions are (a,b) and (c,d) then either b or d should be one

In [28]:
x=np.array([1,2,3])
x.shape

(3,)

In [29]:
y=np.array([1,2,3,4])
y.shape

(4,)

In [27]:
z=np.array([[1],[2],[3]])
z.shape

(3, 1)

In [24]:
sum=np.add(x,y)
sum

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [30]:
sum2=np.add(x,z)
print(sum2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [31]:
ar=np.array([[1],[2]])
ar.shape

(2, 1)

In [32]:
ar2=np.array([[1,2,3],[4,5,6]])
ar2.shape

(2, 3)

In [33]:
print(ar + ar2)

[[2 3 4]
 [6 7 8]]
