In [45]:
import numpy as np

In [46]:
np.random.seed(89)

In [47]:
var=np.random.rand()
var

0.499694320468834

In [48]:
var_1d=np.random.rand(5)
var_1d

array([0.25593713, 0.25810063, 0.09692171, 0.56418511, 0.01599007])

In [49]:
var1_2d=np.random.rand(3,5)
var1_2d

array([[0.15259523, 0.48024773, 0.09987276, 0.41696389, 0.91365081],
       [0.35071951, 0.11460437, 0.71260839, 0.10188615, 0.40570044],
       [0.66548144, 0.13835937, 0.83043309, 0.12319969, 0.58779155]])

In [50]:
var2=np.random.randn()
var2

-0.00487073841865361

In [51]:
#value in range 0 to 1. 1 is not included but 0 is included 
var3=np.random.ranf()
var3

0.9283946209650547

In [52]:
#to input random values of integer type 
#format--> randint(start, end, no. of terms)
var4=np.random.randint(10,20,5)
var4

array([17, 11, 12, 19, 14])

In [53]:
x=np.array([1,2,3,4])
print(x.dtype)

int32


In [54]:
y=np.array([1,2,3,4] , dtype="f")
print(y)
print(y.dtype)

[1. 2. 3. 4.]
float32


In [55]:
z=np.array([1,2,3,4] , dtype=np.float32)
print(y)
print(y.dtype)

[1. 2. 3. 4.]
float32


In [56]:
l=np.array([1,2,3,4], dtype='i')
print(l)
print(l.dtype)

[1 2 3 4]
int32


In [57]:
m=np.array([1,2,3,4], dtype=np.int64)
print(m)
print(m.dtype)

[1 2 3 4]
int64


In [58]:
n=np.array([1,2,1,23]).astype(float)
n

array([ 1.,  2.,  1., 23.])