In [1]:
import numpy as np

SEARCHING - search an array for a certain value and return the indexes that get a match. 'where' keyword is used.

In [2]:
ar= np.array([1,2,3,4,2,5,2,5,6,7])

In [22]:
x=np.where( ar==2 )
print(x)
a=np.array(x)
a=a.reshape(-1)
print(a[1])

(array([1, 4, 6], dtype=int64),)
4


In [4]:
y=np.where( ar/2 == 0)
print(y)

(array([], dtype=int64),)


In [5]:
z=np.where( ar%2 == 0)
print(z)

(array([1, 3, 4, 6, 8], dtype=int64),)


SEARCH SORTED- we perform binary search in the array and rerturn the index where element should be inserted.

In [23]:
arr=np.array([1,2,3,5])

In [24]:
s=np.searchsorted(arr, 4)
print(s)

3


In [25]:
s1=np.searchsorted(arr,6)
print(s1)

4


In [26]:
s2=np.searchsorted(arr, [0,4,5,6], side='right')
print(s2)

[0 3 4 4]


SORT ARRAY

In [29]:
mix=np.random.randint(2,100,10)
np.random.seed(23)
print(mix)

[85 42 75 56 33 78 93 41 92 27]


In [30]:
print(np.sort(mix))

[27 33 41 42 56 75 78 85 92 93]


In [31]:
mixchar=np.array(['a', 'x', 'g', 'u'])
print(mixchar)
print(np.sort(mixchar))

['a' 'x' 'g' 'u']
['a' 'g' 'u' 'x']


In [32]:
mix2d= np.array([[2,5,1],[67,4,0]])
print(np.sort(mix2d))

[[ 1  2  5]
 [ 0  4 67]]


FILTER- to get a specific element out of an existing array and creating a new array from it

In [33]:
src=np.array(['a','b','c','d'])
f=[True, False, False, True]
new_a=src[f]
print(new_a)

['a' 'd']


SHUFFLE

In [35]:
suf=np.array([1,2,3,4,5])
np.random.shuffle(suf)
print(suf)

[5 2 1 3 4]


UNIQUE

In [36]:
uni=np.array([1,2,3,4,2,5,7,2,5,2,6])
x=np.unique(uni)
print(x)

[1 2 3 4 5 6 7]


In [37]:
y=np.unique(uni, return_index=True)
print(y)

(array([1, 2, 3, 4, 5, 6, 7]), array([ 0,  1,  2,  3,  5, 10,  6], dtype=int64))


In [38]:
z=np.unique(uni, return_counts=True)
print(z)

(array([1, 2, 3, 4, 5, 6, 7]), array([1, 4, 1, 1, 2, 1, 1], dtype=int64))


RESIZE- one dimension to multi dimensions array

In [39]:
var2=np.array([1,2,3,4,5,6])
res=np.resize(var2, (2,3))
print(res)

[[1 2 3]
 [4 5 6]]


FLATTEN- multi dimensions to one dimension

In [43]:
var3=np.array([[1,2],[3,4],[5,6]])
print(var3)
print()
print(var3.flatten())
print()
print(var3.flatten(order='F'))

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]

[1 3 5 2 4 6]


RAVEL

In [44]:
var4=np.array([[1,2],[3,4],[5,6]])
print(var4)
print()
print(np.ravel(var4))
print()
print(np.ravel(var4, order="F"))

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]

[1 3 5 2 4 6]
