In [33]:
import numpy as np

In [50]:
np.random.seed(6)
ar=np.random.randint(2,20,5)
print(ar)

[12 11  5 12 15]


In [35]:
print("index 0: ",ar[0]," <= 1st element")
print("index 1: ",ar[1]," <= 2nd element")
print("index 2: ",ar[2]," <= 3rd element")
print("index 3: ",ar[3]," <= 4th element")
print("index 4: ",ar[4]," <= 5th element")

index 0:  13  <= 1st element
index 1:  7  <= 2nd element
index 2:  7  <= 3rd element
index 3:  19  <= 4th element
index 4:  6  <= 5th element


In [36]:
print("negative index -1: ",ar[-1]," <=5th element")
print("negative index -2: ",ar[-2]," <=4th element")
print("negative index -3: ",ar[-3]," <=3rd element")
print("negative index -4: ",ar[-4]," <=2nd element")
print("negative index -5: ",ar[-5]," <=1st element")

negative index -1:  6  <=5th element
negative index -2:  19  <=4th element
negative index -3:  7  <=3rd element
negative index -4:  7  <=2nd element
negative index -5:  13  <=1st element


In [52]:
np.random.seed(61)
ar2d=np.random.randint(2,50,6)
ar2d=ar2d.reshape(2,3)
print(ar2d)

[[37 20 36]
 [18 49 36]]


In [53]:
print("2 nd row 2nd element: ", ar2d[1][1])

2 nd row 2nd element:  49


In [65]:
np.random.seed(45)
arrr=np.random.randint(0,100,12)
ar3d= arrr.reshape(2,2,3)
print(ar3d)

[[[75 30  3]
  [32 95 61]]

 [[85 35 68]
  [15 65 14]]]


In [69]:
print("element at position 2,2,1: ", ar3d[1][1][0])

element at position 2,2,1:  15


Slicing

In [83]:
var=np.array([1,2,3,4,5,6,7])
#index        0,1,2,3,4,5,6
print(var)
print()
print(var.shape)
print()
print("2 to 5", var[1:5])
print()
print("2 to end", var[1:],end="\n \n")
print("start to end with alternate values: ", var[::2])

[1 2 3 4 5 6 7]

(7,)

2 to 5 [2 3 4 5]

2 to end [2 3 4 5 6 7]
 
start to end with alternate values:  [1 3 5 7]


In [85]:
var2=np.array([[1,2,3,4,6,7,8],[5,6,7,8,4,2,1]])
print(var2[0,1:5])
print(var2[1,::2])

[2 3 4 6]
[5 7 4 1]


In [87]:
np.random.seed(89)
var3=np.random.randint(2,100,(7*3*3))
var3=var3.reshape(3, 3, 7)
print(var3, end="\n\n")
print(var3[2,1,::2])

[[[21 32  6 24 45 60 10]
  [84 35 28 61 96 90 63]
  [66 89 24 54 72 58 88]]

 [[99 65  9 88 47 33 21]
  [83 95 83 42 71 73 33]
  [31 18 29 15 60 25 79]]

 [[95 35 52 70 96 94 14]
  [54 11 84 90 51 78 78]
  [81 69 93 11 12 66  4]]]

[54 84 51 78]
