In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
#np.insert(kisme?, kha pe?, aur kya?)
var=np.insert(x,2,40 )
print(var)

[ 1  2 40  3  4]


In [5]:
var2=np.insert(x,(2,4),80)
print(var2)

[ 1  2 80  3  4 80]


In [9]:
var4=np.insert(x, 3, 6.5)
print(var4)

[1 2 3 6 4]


In [18]:
p=np.append(x, 6.5)
print("x: ",x)
print(p)

x:  [1 2 3 4]
[1.  2.  3.  4.  6.5]


In [6]:
y=np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [10]:
var3=np.insert(y,5,11)
print(var3)

[ 1  2  3  4  5 11  6]


In [16]:
var5=np.insert(y, 2, 6, axis=0)
print(var5)

[[1 2 3]
 [4 5 6]
 [6 6 6]]


In [13]:
var6=np.insert(y, 1, 7, axis=1)
print(var6)

[[1 7 2 3]
 [4 7 5 6]]


In [23]:
q=np.append(y,[[1.2, 2.01,3.3]], axis=0)
print(y)
print(q)

[[1 2 3]
 [4 5 6]]
[[1.   2.   3.  ]
 [4.   5.   6.  ]
 [1.2  2.01 3.3 ]]


In [32]:
r=np.append(y,[[1.1],[2.2]], axis=1)
print(r)

[[1.  2.  3.  1.1]
 [4.  5.  6.  2.2]]


DELETE

In [31]:
d=np.array([1,2,3,4,5])
print(d)
d2=np.delete(d,3)
print(d2)

[1 2 3 4 5]
[1 2 3 5]
