In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5,6,7,8])
print(x)

[1 2 3 4 5 6 7 8]


In [4]:
for i in x:
    print(i)

1
2
3
4
5
6
7
8


In [7]:
k=np.array([[1,2,3],[4,5,6]])
print(k)
for i in k:
    print(i)
#its giving array as an output 

[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]


In [5]:
y=np.array([[1,2,3],[4,5,6]])
print(y)
for i in y:
    for j in i:
        print(j,end=' ')
    print()

[[1 2 3]
 [4 5 6]]
1 2 3 
4 5 6 


In [13]:
np.random.seed(88)
z=np.random.randint(2,50,27)
z=z.reshape(3, 3, 3)
print(z)
print()
for i in z:
    for j in i:
        for m in j:
            print(m, end='  ')
        print()
    print()


[[[26 34 17]
  [44 22 39]
  [35  7 46]]

 [[36 35 13]
  [ 6  9 28]
  [27  9 41]]

 [[ 8 12 24]
  [31 15 37]
  [15  3 42]]]

26  34  17  
44  22  39  
35  7  46  

36  35  13  
6  9  28  
27  9  41  

8  12  24  
31  15  37  
15  3  42  



In [19]:
print(z, end='\n\n')
for i in np.nditer(z):
    print(i)

[[[26 34 17]
  [44 22 39]
  [35  7 46]]

 [[36 35 13]
  [ 6  9 28]
  [27  9 41]]

 [[ 8 12 24]
  [31 15 37]
  [15  3 42]]]

26
34
17
44
22
39
35
7
46
36
35
13
6
9
28
27
9
41
8
12
24
31
15
37
15
3
42


In [20]:
print(z, end='\n\n')
for i in np.nditer(z,flags=['buffered'] ,op_dtypes='S'):
    print(i)

[[[26 34 17]
  [44 22 39]
  [35  7 46]]

 [[36 35 13]
  [ 6  9 28]
  [27  9 41]]

 [[ 8 12 24]
  [31 15 37]
  [15  3 42]]]

b'26'
b'34'
b'17'
b'44'
b'22'
b'39'
b'35'
b'7'
b'46'
b'36'
b'35'
b'13'
b'6'
b'9'
b'28'
b'27'
b'9'
b'41'
b'8'
b'12'
b'24'
b'31'
b'15'
b'37'
b'15'
b'3'
b'42'


In [23]:

for i,d in np.ndenumerate(z):
    print("index: ",i," element: ",d)

index:  (0, 0, 0)  element:  26
index:  (0, 0, 1)  element:  34
index:  (0, 0, 2)  element:  17
index:  (0, 1, 0)  element:  44
index:  (0, 1, 1)  element:  22
index:  (0, 1, 2)  element:  39
index:  (0, 2, 0)  element:  35
index:  (0, 2, 1)  element:  7
index:  (0, 2, 2)  element:  46
index:  (1, 0, 0)  element:  36
index:  (1, 0, 1)  element:  35
index:  (1, 0, 2)  element:  13
index:  (1, 1, 0)  element:  6
index:  (1, 1, 1)  element:  9
index:  (1, 1, 2)  element:  28
index:  (1, 2, 0)  element:  27
index:  (1, 2, 1)  element:  9
index:  (1, 2, 2)  element:  41
index:  (2, 0, 0)  element:  8
index:  (2, 0, 1)  element:  12
index:  (2, 0, 2)  element:  24
index:  (2, 1, 0)  element:  31
index:  (2, 1, 1)  element:  15
index:  (2, 1, 2)  element:  37
index:  (2, 2, 0)  element:  15
index:  (2, 2, 1)  element:  3
index:  (2, 2, 2)  element:  42
