In [20]:
import numpy as np

In [21]:
x=np.array([1,2,3,4])

In [22]:
y=np.array([9,8,7,6])

In [23]:
z=np.concatenate((x,y))
print(z)

[1 2 3 4 9 8 7 6]


In [24]:
p=np.array([[1,2],[3,4]])

In [25]:
q=np.array([[9,8],[7,6]])

In [26]:
r=np.concatenate((p, q), axis=0)
print(r)

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [27]:
s=np.concatenate((p, q), axis=1)
print(s)

[[1 2 9 8]
 [3 4 7 6]]


In [28]:
l=np.array([1,2,3,4])

In [29]:
m=np.array([9,8,7,6])

In [30]:
o=np.stack((l,m), axis=1) #height 1 1 
print(o)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [31]:
i=np.stack((l,m), axis=0)
print(i)

[[1 2 3 4]
 [9 8 7 6]]


In [32]:
a=np.vstack((l, m)) #column
print(a)

[[1 2 3 4]
 [9 8 7 6]]


In [18]:
b=np.hstack((l, m)) #row
print(b)

[1 2 3 4 9 8 7 6]


In [19]:
c=np.dstack((l, m)) #height
print(c)

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]
