In [1]:
import numpy as np

In [4]:
ar=np.array([1,4,9,16,25])
print(ar.ndim)
print(ar.shape)

1
(5,)


In [7]:
arr=np.array([[1,4,9,16],[25,36,49,64]])
print(arr)
print(arr.shape)

[[ 1  4  9 16]
 [25 36 49 64]]
(2, 4)


In [8]:
multi_ar=np.array([1,4,9], ndmin=4)
multi_ar

array([[[[1, 4, 9]]]])

In [9]:
print(multi_ar)
print(multi_ar.shape)

[[[[1 4 9]]]]
(1, 1, 1, 3)


Reshape

In [10]:
x=np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [14]:
x_2D=x.reshape(3,2)
x_2D

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
x_2D.ndim

2

In [16]:
y=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
y_3D=y.reshape(2,3,2)
y_3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [18]:
y_3D.ndim

3

In [19]:
one=y_3D.reshape(-1)
one

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
one.ndim

1