In [1]:
import numpy as np

In [3]:
#all elements 0
zero=np.zeros(4)
print(zero)

[0. 0. 0. 0.]


In [6]:
zero_2=np.zeros((4,5))
print(zero_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
#all elements as 1
one=np.ones(4)
print(one)

[1. 1. 1. 1.]


In [10]:
one_2=np.ones((3,4))
print(one_2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
#empty array
emp=np.empty(3)
print(emp)

[ 8.33460218e-312  0.00000000e+000 -4.94065646e-324]


In [17]:
emp_2=np.empty((3,3))
print(emp_2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
#fill the array with same diagonal elements
diag=np.eye(3,4)
print(diag)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [32]:
diag_1=np.eye(3)
print(diag_1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
#fill elements with linear space
#linspace(start, end, no. of elements) ---. start and end are inclusive
lin=np.linspace(0,20,5).astype(int)
print(lin)  

[ 0  5 10 15 20]


In [35]:
#default size is 50
lin_2=np.linspace(0,5)
print(lin_2)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]
