In [1]:
import numpy as np

In [3]:
x=np.array([1,2,3,4,5,6])

In [6]:
ar=np.array_split(x,3)
print(ar)
print()
print(type(ar))
print()
print(ar[0])

[array([1, 2]), array([3, 4]), array([5, 6])]

<class 'list'>

[1 2]


In [13]:
y=np.array([[1,2],[3,4],[5,6]])
print(y)
print()
arr=np.array_split(y,3)
print(arr)
print()
arr_new=np.array_split(y,3, axis=1)
print(arr_new[0])

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[[1]
 [3]
 [5]]


In [15]:
z=np.array([[1,2,9],[3,4,8],[5,6,7]])
print(z)
print()
arr=np.array_split(z,3)
print(arr)
print()
arr_new=np.array_split(z,3, axis=1)
print(arr_new)
print()
print(arr_new[0])

[[1 2 9]
 [3 4 8]
 [5 6 7]]

[array([[1, 2, 9]]), array([[3, 4, 8]]), array([[5, 6, 7]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([[9],
       [8],
       [7]])]

[[1]
 [3]
 [5]]
